#!/bin/bash
git add . # tiek pieteiktas adreses 'uzmanīšanai'
git config --global user.name cilingarjans
git config --global user.email chilingaryan007@gmail.com
#git commit -m 'class 04'
git commit -m "class_$1"
git push origin main
